version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/Docker"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "python"
        versions: ["3.13.x"]
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
